<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class BanksSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $banks = [
            [
                'bank_code' => 'HBL',
                'bank_name' => 'Habib Bank Limited',
                'bank_short_name' => 'HBL',
                'branch_code' => '0001',
                'branch_name' => 'Main Branch',
                'account_number' => '10011234567890',
                'account_title' => 'QG Trading Company',
                'account_type' => 'current',
                'currency' => 'PKR',
                'iban' => 'PK36HABB0010011234567890',
                'swift_code' => 'HABBPKKA',
                'routing_number' => null,
                'address1' => 'I.I. Chundrigar Road',
                'address2' => 'Near State Bank of Pakistan',
                'city' => 'Karachi',
                'state' => 'Sindh',
                'country' => 'Pakistan',
                'postal_code' => '74000',
                'phone_number' => '+92-21-1111-4000',
                'fax_number' => '+92-21-32412345',
                'email' => 'info@hbl.com',
                'contact_person' => 'Ahmed Ali Khan',
                'contact_person_phone' => '+92-21-32412300',
                'contact_person_email' => 'ahmed.khan@hbl.com',
                'bank_gl_account' => '1001001',
                'status' => 'active',
                'ou_id' => 1,
                'ou_name' => 'QG Trading Head Office',
                'created_by' => 'System',
                'updated_by' => 'System',
                'creation_date' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'bank_code' => 'ABL',
                'bank_name' => 'Allied Bank Limited',
                'bank_short_name' => 'Allied Bank',
                'branch_code' => '0256',
                'branch_name' => 'Gulberg Branch',
                'account_number' => '0010256789012',
                'account_title' => 'QG Trading Company - Operations',
                'account_type' => 'current',
                'currency' => 'PKR',
                'iban' => 'PK24ABPA0010256789012',
                'swift_code' => 'ABPAPKKA',
                'routing_number' => null,
                'address1' => 'MM Alam Road, Gulberg III',
                'address2' => 'Near Liberty Market',
                'city' => 'Lahore',
                'state' => 'Punjab',
                'country' => 'Pakistan',
                'postal_code' => '54660',
                'phone_number' => '+92-42-111-225-225',
                'fax_number' => '+92-42-35777889',
                'email' => 'gulberg@abl.com',
                'contact_person' => 'Fatima Sheikh',
                'contact_person_phone' => '+92-42-35777800',
                'contact_person_email' => 'fatima.sheikh@abl.com',
                'bank_gl_account' => '1001002',
                'status' => 'active',
                'ou_id' => 1,
                'ou_name' => 'QG Trading Head Office',
                'created_by' => 'System',
                'updated_by' => 'System',
                'creation_date' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'bank_code' => 'MCB',
                'bank_name' => 'MCB Bank Limited',
                'bank_short_name' => 'MCB',
                'branch_code' => '0789',
                'branch_name' => 'Defence Branch',
                'account_number' => '0789123456789',
                'account_title' => 'QG Trading Company - Export',
                'account_type' => 'current',
                'currency' => 'USD',
                'iban' => 'PK86MUCB0789123456789',
                'swift_code' => 'MUCBPKKA',
                'routing_number' => null,
                'address1' => 'Khayaban-e-Rahat, Phase VI',
                'address2' => 'DHA Defence',
                'city' => 'Karachi',
                'state' => 'Sindh',
                'country' => 'Pakistan',
                'postal_code' => '75500',
                'phone_number' => '+92-21-111-000-622',
                'fax_number' => '+92-21-35311234',
                'email' => 'defence@mcb.com.pk',
                'contact_person' => 'Muhammad Usman',
                'contact_person_phone' => '+92-21-35311200',
                'contact_person_email' => 'usman@mcb.com.pk',
                'bank_gl_account' => '1001003',
                'status' => 'active',
                'ou_id' => 1,
                'ou_name' => 'QG Trading Head Office',
                'created_by' => 'System',
                'updated_by' => 'System',
                'creation_date' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'bank_code' => 'UBL',
                'bank_name' => 'United Bank Limited',
                'bank_short_name' => 'UBL',
                'branch_code' => '1425',
                'branch_name' => 'Johar Town Branch',
                'account_number' => '142500987654321',
                'account_title' => 'QG Trading Company - Payroll',
                'account_type' => 'savings',
                'currency' => 'PKR',
                'iban' => 'PK47UNIL0142500987654321',
                'swift_code' => 'UNILPKKA',
                'routing_number' => null,
                'address1' => 'Main Boulevard, Johar Town',
                'address2' => 'Near Emporium Mall',
                'city' => 'Lahore',
                'state' => 'Punjab',
                'country' => 'Pakistan',
                'postal_code' => '54782',
                'phone_number' => '+92-42-111-825-888',
                'fax_number' => '+92-42-35951234',
                'email' => 'johartown@ubl.com.pk',
                'contact_person' => 'Sara Ahmed',
                'contact_person_phone' => '+92-42-35951200',
                'contact_person_email' => 'sara.ahmed@ubl.com.pk',
                'bank_gl_account' => '1001004',
                'status' => 'active',
                'ou_id' => 1,
                'ou_name' => 'QG Trading Head Office',
                'created_by' => 'System',
                'updated_by' => 'System',
                'creation_date' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'bank_code' => 'NBP',
                'bank_name' => 'National Bank of Pakistan',
                'bank_short_name' => 'NBP',
                'branch_code' => '0142',
                'branch_name' => 'Saddar Branch',
                'account_number' => '0142567890123456',
                'account_title' => 'QG Trading Company - General',
                'account_type' => 'current',
                'currency' => 'PKR',
                'iban' => 'PK04NBPA0142567890123456',
                'swift_code' => 'NBPAPKKA',
                'routing_number' => null,
                'address1' => 'Abdullah Haroon Road',
                'address2' => 'Saddar',
                'city' => 'Karachi',
                'state' => 'Sindh',
                'country' => 'Pakistan',
                'postal_code' => '74400',
                'phone_number' => '+92-21-111-627-627',
                'fax_number' => '+92-21-32278900',
                'email' => 'saddar@nbp.com.pk',
                'contact_person' => 'Ali Hassan',
                'contact_person_phone' => '+92-21-32278901',
                'contact_person_email' => 'ali.hassan@nbp.com.pk',
                'bank_gl_account' => '1001005',
                'status' => 'active',
                'ou_id' => 1,
                'ou_name' => 'QG Trading Head Office',
                'created_by' => 'System',
                'updated_by' => 'System',
                'creation_date' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        DB::table('banks')->insert($banks);
    }
}